### PR TITLE
Update to .NET 5

### PR DESCRIPTION
**Pull request by cndouglas**

### CODE REVIEW

**Review by bgrainger — APPROVED** [review]
FWIW, you could convert https://github.com/Faithlife/FaithlifeTesting/blob/e2fc6d98c53d4770c0cbca4d78c80384b1e6083e/tools/Build/Build.cs to a single top-level statement: https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#top-level-statements

**Comment by michael-sterling** [comment]
```
Run ./build.sh package
CSC : error AD0001: Analyzer 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.IdentifiersShouldNotContainTypeNames' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'. [/home/runner/work/FaithlifeTesting/FaithlifeTesting/tools/Build/Build.csproj]
Error: Process completed with exit code 1.
```

That wasn't happening before the "top-level statement" commit.

**Comment by cndouglas** [comment]
Updated the analyzers, based on https://github.com/Faithlife/FaithlifeBuild/commit/588ed52b067783743feafca7c9f839ca53523870

**Comment by michael-sterling** [comment]
🤣 

> error CA1711: Either replace the suffix 'Ex' in type name AssertEx with the suggested numeric alternate '2' or provide a more meaningful suffix that distinguishes it from the type it replaces 

https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1711

It thinks `Assert2` would be better than `AssertEx`!

I hope I never see the code which caused someone to want that in the analyzer.

I suggest we turn that rule off.

**Pull request merged**
